[package]
name = "pinar"
version = "0.1.0"
authors = ["Sebastien Chapuis <sebastien@chapu.is>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[profile.dev]
panic = "unwind"

[profile.release]
panic = "unwind"

[dependencies]
#napi-sys = "0.1"
napi-sys = { path = "../napi-sys" }
parking_lot = "0.7"
#slotmap = "0.3"
# slab = "0.4"
failure = "0.1.3"
# smallvec = "0.6.7"
