[package]
name = "pinar"
version = "0.1.0"
authors = ["Sebastien Chapuis <sebastien@chapu.is>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
#napi-sys = "0.1"
napi-sys = { path = "../napi-sys" }
